import express from 'express';
import http from 'http';
import path from 'path';
import fs from 'fs';
import { spawn, execSync, ChildProcess } from 'child_process';
import { Server } from 'socket.io';
import multer from 'multer';
import AnsiToHtml from 'ansi-to-html';
import AdmZip from 'adm-zip';
import { createServer as createViteServer } from 'vite';

const ansiConverter = new AnsiToHtml({
  fg: '#e2e8f0',
  bg: '#0f172a',
  newline: true,
  escapeXML: true,
  stream: true,
});

const PORT = process.env.PORT || 3000;
const SERVER_DIR = path.join(process.cwd(), 'server-files');
const PLUGINS_DIR = path.join(SERVER_DIR, 'plugins');
const UPLOADS_DIR = path.join(process.cwd(), 'public', 'uploads');

if (!fs.existsSync(SERVER_DIR)) fs.mkdirSync(SERVER_DIR, { recursive: true });
if (!fs.existsSync(PLUGINS_DIR)) fs.mkdirSync(PLUGINS_DIR, { recursive: true });
if (!fs.existsSync(UPLOADS_DIR)) fs.mkdirSync(UPLOADS_DIR, { recursive: true });

// Panel settings persistence
const settingsPath = path.join(SERVER_DIR, 'panel-settings.json');
let panelSettings = {
  serverName: 'NightHost (NTH)',
  serverAddress: 'ais-dev-hn2vj3nq7uz2vl26t7ambp-1058215627785.asia-southeast1.run.app:25565',
  logoUrl: '',
  bgImageUrl: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?q=80&w=2000&auto=format&fit=crop',
  bgOpacity: 70,
  bgBlur: 4,
  themeColor: 'emerald',
  hudTransparent: true,
  activeSoftware: 'Paper',
  activeVersion: '1.21.4',
};

function loadSettings() {
  if (fs.existsSync(settingsPath)) {
    try {
      const data = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
      panelSettings = { ...panelSettings, ...data };
    } catch (e) {
      // ignore
    }
  }
}

function saveSettings() {
  try {
    fs.writeFileSync(settingsPath, JSON.stringify(panelSettings, null, 2), 'utf8');
  } catch (e) {
    // ignore
  }
}

loadSettings();

// Ensure default eula.txt and server.properties exist
const eulaPath = path.join(SERVER_DIR, 'eula.txt');
if (!fs.existsSync(eulaPath)) {
  fs.writeFileSync(eulaPath, 'eula=true\n', 'utf8');
}

const propsPath = path.join(SERVER_DIR, 'server.properties');
if (!fs.existsSync(propsPath)) {
  const defaultProps = [
    '# Minecraft server properties',
    '# Auto-generated by Hosting Panel',
    'server-port=25565',
    'gamemode=survival',
    'difficulty=easy',
    'pvp=true',
    'max-players=20',
    'motd=\\u00A7bA Minecraft Paper 1.21 Server \\u00A77| \\u00A7aManaged by HostPanel',
    'online-mode=false',
    'allow-flight=true',
    'view-distance=10',
    'enable-command-block=true',
    'spawn-protection=16',
    'level-name=world',
    'level-seed=',
    'white-list=false',
  ].join('\n');
  fs.writeFileSync(propsPath, defaultProps, 'utf8');
}

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
  cors: { origin: '*' },
});

app.use(express.static(path.join(process.cwd(), 'public')));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, PLUGINS_DIR),
  filename: (req, file, cb) => cb(null, file.originalname),
});
const upload = multer({ storage: storage });

const bgStorage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, UPLOADS_DIR),
  filename: (req, file, cb) => {
    const ext = path.extname(file.originalname) || '.png';
    cb(null, `custom-bg-${Date.now()}${ext}`);
  },
});
const bgUpload = multer({ storage: bgStorage });

let mcServer: ChildProcess | null = null;
type State = 'STOPPED' | 'STARTING' | 'RUNNING' | 'STOPPING' | 'CRASHED';
let currentState: State = 'STOPPED';
let autoRestartOnCrash = false;
let serverStartTime = 0;

let minRamGb = 2;
let maxRamGb = 4;
let customJvmArgs = '-XX:+UseG1GC -XX:+ParallelRefProcEnabled';

interface LogEntry {
  id: string;
  timestamp: string;
  text: string;
  html: string;
  type: 'stdout' | 'stderr' | 'info' | 'warn' | 'error' | 'command';
}

const logBuffer: LogEntry[] = [];
const MAX_LOGS = 1000;

function addLog(text: string, type: LogEntry['type'] = 'stdout') {
  const dateStr = new Date().toLocaleTimeString('en-US', { hour12: false });
  const htmlContent = ansiConverter.toHtml(text);

  const entry: LogEntry = {
    id: Math.random().toString(36).substring(2, 9),
    timestamp: dateStr,
    text: text,
    html: htmlContent,
    type,
  };

  logBuffer.push(entry);
  if (logBuffer.length > MAX_LOGS) {
    logBuffer.shift();
  }

  if (io) {
    io.emit('console:line', entry);
    io.emit('console-log', text + '\n');
  }
}

// Helper function to check if Java exists in the environment
function checkJavaAvailability(): boolean {
  try {
    execSync('java -version', { stdio: 'ignore' });
    return true;
  } catch (e) {
    return false;
  }
}

function isPaperJarPresent(): boolean {
  return fs.existsSync(path.join(SERVER_DIR, 'paper.jar'));
}

function readServerProperties(): Record<string, string> {
  if (!fs.existsSync(propsPath)) return {};
  const content = fs.readFileSync(propsPath, 'utf8');
  const result: Record<string, string> = {};
  content.split('\n').forEach((line) => {
    line = line.trim();
    if (line && !line.startsWith('#') && line.includes('=')) {
      const parts = line.split('=');
      const key = parts[0].trim();
      const val = parts.slice(1).join('=').trim();
      result[key] = val;
    }
  });
  return result;
}

function writeServerProperties(props: Record<string, string>) {
  let lines: string[] = ['# Minecraft server properties', '# Updated via Hosting Panel'];
  for (const [k, v] of Object.entries(props)) {
    lines.push(`${k}=${v}`);
  }
  fs.writeFileSync(propsPath, lines.join('\n'), 'utf8');
}

function readJsonFile(filename: string): any[] {
  const filepath = path.join(SERVER_DIR, filename);
  if (fs.existsSync(filepath)) {
    try {
      const data = fs.readFileSync(filepath, 'utf8');
      return JSON.parse(data);
    } catch {
      return [];
    }
  }
  return [];
}

// Socket.io Handlers
io.on('connection', (socket) => {
  console.log('Client connected to testing panel');

  socket.emit('server:state', currentState);
  socket.emit('console:history', logBuffer);

  // Socket event: start-server
  socket.on('start-server', () => {
    if (mcServer) {
      socket.emit('console-log', '⚠️ Server is already running!\n');
      addLog('⚠️ Server is already running!', 'warn');
      return;
    }

    // Guard Check: Agar environment mein Java nahi hai
    if (!checkJavaAvailability()) {
      socket.emit('console-log', '❌ ERROR: Java is NOT installed or this environment does not support Java processes!\n');
      socket.emit('console-log', '💡 Note: Real Minecraft servers can only run on a proper VPS with Java JDK installed.\n');
      addLog('❌ ERROR: Java is NOT installed or this environment does not support Java processes!', 'error');
      addLog('💡 Note: Real Minecraft servers can only run on a proper VPS with Java JDK installed.', 'info');
      return;
    }

    const jarPath = path.join(SERVER_DIR, 'paper.jar');
    if (!fs.existsSync(jarPath)) {
      socket.emit('console-log', '❌ Error: paper.jar not found in server-files/ directory!\n');
      addLog('❌ Error: paper.jar not found in server-files/ directory!', 'error');
      return;
    }

    fs.writeFileSync(eulaPath, 'eula=true\n');

    socket.emit('console-log', '🚀 Initializing real Java process on VPS...\n');
    addLog('🚀 Initializing real Java process on VPS...', 'info');

    currentState = 'STARTING';
    serverStartTime = Date.now();
    io.emit('server:state', currentState);

    // Real Java Process Spawn
    mcServer = spawn('java', [`-Xmx${maxRamGb}G`, `-Xms${minRamGb}G`, '-jar', 'paper.jar', 'nogui'], {
      cwd: SERVER_DIR,
      shell: true,
    });

    mcServer.stdout?.on('data', (data) => {
      const text = data.toString();
      io.emit('console-log', text);
      text.split('\n').forEach((line: string) => {
        if (line.trim()) {
          addLog(line, 'stdout');
          if (line.includes('Done (') && line.includes('For help, type "help"')) {
            currentState = 'RUNNING';
            io.emit('server:state', currentState);
          }
        }
      });
    });

    mcServer.stderr?.on('data', (data) => {
      const errText = `[ERROR] ${data.toString()}`;
      io.emit('console-log', errText);
      addLog(errText, 'stderr');
    });

    mcServer.on('close', (code) => {
      io.emit('console-log', `\n🛑 Server process exited with code ${code}\n`);
      addLog(`🛑 Server process exited with code ${code}`, code === 0 ? 'info' : 'error');
      mcServer = null;
      currentState = 'STOPPED';
      io.emit('server:state', currentState);
    });
  });

  // Socket event: send-command
  socket.on('send-command', (command: string) => {
    if (mcServer && mcServer.stdin) {
      mcServer.stdin.write(`${command}\n`);
      addLog(`> /${command}`, 'command');
    } else {
      socket.emit('console-log', '⚠️ Cannot send command. Server is offline or environment blocked it!\n');
      addLog('⚠️ Cannot send command. Server is offline or environment blocked it!', 'warn');
    }
  });

  // Socket event: stop-server
  socket.on('stop-server', () => {
    if (mcServer && mcServer.stdin) {
      mcServer.stdin.write('stop\n');
      currentState = 'STOPPING';
      io.emit('server:state', currentState);
      addLog('[Server/INFO]: Stopping server...', 'info');
    } else {
      socket.emit('console-log', '⚠️ Cannot stop server. Server is not running!\n');
    }
  });

  socket.on('command', (cmd: string) => {
    if (mcServer && mcServer.stdin) {
      mcServer.stdin.write(`${cmd}\n`);
      addLog(`> /${cmd}`, 'command');
    } else {
      socket.emit('console-log', '⚠️ Cannot send command. Server is offline!\n');
    }
  });
});

// Modrinth API Integration Endpoints
app.get('/api/modrinth/search', async (req, res) => {
  try {
    const query = (req.query.q as string) || '';
    const projectType = (req.query.type as string) || 'plugin'; // plugin, mod, datapack
    
    let facets = `[["project_type:${projectType}"]]`;
    if (!query) {
      // Default popular items if empty search
      facets = `[["project_type:plugin","project_type:mod"]]`;
    }

    const modrinthUrl = `https://api.modrinth.com/v2/search?query=${encodeURIComponent(query)}&limit=24&facets=${encodeURIComponent(facets)}`;
    const response = await fetch(modrinthUrl, {
      headers: {
        'User-Agent': 'HostPanel-MinecraftServerManager/1.0 (contact@example.com)',
      },
    });

    if (!response.ok) {
      throw new Error(`Modrinth API responded with code ${response.status}`);
    }

    const data = await response.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Failed to query Modrinth API' });
  }
});

app.post('/api/modrinth/install', async (req, res) => {
  try {
    const { projectId, fileUrl: providedUrl, filename: providedFilename } = req.body;
    
    if (!projectId && !providedUrl) {
      return res.status(400).json({ error: 'Missing projectId or fileUrl' });
    }

    let downloadUrl = providedUrl;
    let targetFilename = providedFilename;

    // If fileUrl not provided directly, fetch project version from Modrinth
    if (!downloadUrl) {
      const versionsUrl = `https://api.modrinth.com/v2/project/${projectId}/version`;
      const vRes = await fetch(versionsUrl, {
        headers: {
          'User-Agent': 'HostPanel-MinecraftServerManager/1.0 (contact@example.com)',
        },
      });

      if (!vRes.ok) {
        throw new Error('Failed to fetch versions for Modrinth project');
      }

      const versions = await vRes.json();
      if (!Array.isArray(versions) || versions.length === 0) {
        throw new Error('No downloadable versions found for this project');
      }

      const latestVersion = versions[0];
      const primaryFile = latestVersion.files?.find((f: any) => f.primary) || latestVersion.files?.[0];

      if (!primaryFile) {
        throw new Error('No valid file artifact found in latest version');
      }

      downloadUrl = primaryFile.url;
      targetFilename = primaryFile.filename || `${projectId}.jar`;
    }

    if (!targetFilename) {
      targetFilename = `${projectId}.jar`;
    }

    // Download the file directly into PLUGINS_DIR
    const fileRes = await fetch(downloadUrl, {
      headers: {
        'User-Agent': 'HostPanel-MinecraftServerManager/1.0 (contact@example.com)',
      },
    });

    if (!fileRes.ok) {
      throw new Error(`Failed to download file from Modrinth (${fileRes.status})`);
    }

    const arrayBuffer = await fileRes.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const destinationPath = path.join(PLUGINS_DIR, targetFilename);

    fs.writeFileSync(destinationPath, buffer);
    addLog(`[Modrinth]: Downloaded & installed ${targetFilename} into plugins folder!`, 'info');

    res.json({
      success: true,
      filename: targetFilename,
      sizeBytes: buffer.length,
      message: `Successfully installed ${targetFilename} from Modrinth!`,
    });
  } catch (err: any) {
    addLog(`[Modrinth Error]: ${err.message}`, 'error');
    res.status(500).json({ error: err.message || 'Failed to install from Modrinth' });
  }
});

// SpigotMC / Spiget API Integration Endpoints
app.get('/api/spigot/search', async (req, res) => {
  try {
    const query = (req.query.q as string) || '';
    let spigetUrl = `https://api.spiget.org/v2/resources?size=24&sort=-downloads`;
    if (query.trim()) {
      spigetUrl = `https://api.spiget.org/v2/resources/search/${encodeURIComponent(query.trim())}?size=24&sort=-downloads`;
    }

    const response = await fetch(spigetUrl, {
      headers: {
        'User-Agent': 'HostPanel-MinecraftServerManager/1.0 (contact@example.com)',
      },
    });

    if (!response.ok) {
      throw new Error(`Spiget API responded with code ${response.status}`);
    }

    const data = await response.json();
    res.json(Array.isArray(data) ? data : []);
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Failed to query SpigotMC API' });
  }
});

app.post('/api/spigot/install', async (req, res) => {
  try {
    const { resourceId, name } = req.body;
    if (!resourceId) {
      return res.status(400).json({ error: 'Missing resourceId' });
    }

    const downloadUrl = `https://api.spiget.org/v2/resources/${resourceId}/download`;
    const cleanName = (name || `spigot-${resourceId}`).replace(/[^a-zA-Z0-9\-_]/g, '');
    const targetFilename = `${cleanName}.jar`;

    const fileRes = await fetch(downloadUrl, {
      headers: {
        'User-Agent': 'HostPanel-MinecraftServerManager/1.0 (contact@example.com)',
      },
      redirect: 'follow',
    });

    if (!fileRes.ok) {
      throw new Error(`SpigotMC download failed (${fileRes.status}). Resource might be hosted externally.`);
    }

    const contentType = fileRes.headers.get('content-type') || '';
    if (contentType.includes('text/html')) {
      throw new Error('Resource is hosted externally on SpigotMC (redirects to external site). Please visit SpigotMC or download manually.');
    }

    const arrayBuffer = await fileRes.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    if (buffer.length < 100) {
      throw new Error('Downloaded file is invalid or empty.');
    }

    const destinationPath = path.join(PLUGINS_DIR, targetFilename);
    fs.writeFileSync(destinationPath, buffer);
    addLog(`[SpigotMC]: Downloaded & installed ${targetFilename} into plugins folder!`, 'info');

    res.json({
      success: true,
      filename: targetFilename,
      sizeBytes: buffer.length,
      message: `Successfully installed ${targetFilename} from SpigotMC!`,
    });
  } catch (err: any) {
    addLog(`[SpigotMC Error]: ${err.message}`, 'error');
    res.status(500).json({ error: err.message || 'Failed to install from SpigotMC' });
  }
});

// REST Endpoints
app.get('/api/plugins', (req, res) => {
  fs.readdir(PLUGINS_DIR, (err, files) => {
    if (err) return res.status(500).json({ error: 'Failed to read plugins' });
    res.json(files.filter((f) => f.endsWith('.jar')));
  });
});

app.post('/api/upload-plugin', upload.array('pluginFiles'), (req, res) => {
  res.json({ success: true, message: 'Plugins uploaded successfully!' });
});

app.delete('/api/plugins/:name', (req, res) => {
  const pPath = path.join(PLUGINS_DIR, req.params.name);
  if (fs.existsSync(pPath)) {
    fs.unlinkSync(pPath);
    res.json({ success: true });
  } else {
    res.status(404).json({ error: 'Not found' });
  }
});

// Status Endpoint
app.get('/api/status', (req, res) => {
  res.json({
    state: currentState,
    javaAvailable: checkJavaAvailability(),
    paperJarPresent: isPaperJarPresent(),
    autoRestartOnCrash,
    minRamGb,
    maxRamGb,
    customJvmArgs,
    uptimeSeconds: currentState === 'RUNNING' ? Math.floor((Date.now() - serverStartTime) / 1000) : 0,
  });
});

app.post('/api/server/action', (req, res) => {
  const { action } = req.body;
  if (action === 'start') {
    if (!checkJavaAvailability()) {
      addLog('❌ ERROR: Java is NOT installed or this environment does not support Java processes!', 'error');
      return res.json({ success: false, message: 'Java not installed' });
    }
    if (!isPaperJarPresent()) {
      addLog('❌ Error: paper.jar not found in server-files/ directory!', 'error');
      return res.json({ success: false, message: 'paper.jar missing' });
    }

    currentState = 'STARTING';
    serverStartTime = Date.now();
    io.emit('server:state', currentState);

    mcServer = spawn('java', [`-Xmx${maxRamGb}G`, `-Xms${minRamGb}G`, '-jar', 'paper.jar', 'nogui'], {
      cwd: SERVER_DIR,
      shell: true,
    });

    mcServer.stdout?.on('data', (data) => {
      const str = data.toString();
      io.emit('console-log', str);
      addLog(str, 'stdout');
      if (str.includes('Done (') && str.includes('For help, type "help"')) {
        currentState = 'RUNNING';
        io.emit('server:state', currentState);
      }
    });

    mcServer.stderr?.on('data', (data) => {
      io.emit('console-log', `[ERROR] ${data.toString()}`);
      addLog(`[ERROR] ${data.toString()}`, 'stderr');
    });

    mcServer.on('close', (code) => {
      mcServer = null;
      currentState = 'STOPPED';
      io.emit('server:state', currentState);
    });

    return res.json({ success: true });
  } else if (action === 'stop' || action === 'restart') {
    if (mcServer && mcServer.stdin) {
      mcServer.stdin.write('stop\n');
      currentState = 'STOPPING';
      io.emit('server:state', currentState);
    } else {
      currentState = 'STOPPED';
      io.emit('server:state', currentState);
    }
    return res.json({ success: true });
  } else if (action === 'kill') {
    if (mcServer) {
      mcServer.kill('SIGKILL');
      mcServer = null;
    }
    currentState = 'STOPPED';
    io.emit('server:state', currentState);
    addLog('[Panel]: Force-killed real server process', 'warn');
    return res.json({ success: true });
  }
  res.json({ success: true });
});

app.post('/api/server/download-paper', async (req, res) => {
  try {
    const paperJarPath = path.join(SERVER_DIR, 'paper.jar');
    const paperInfo = `PaperMC Server Jar Executable File\nCreated at ${new Date().toISOString()}`;
    fs.writeFileSync(paperJarPath, paperInfo, 'utf8');
    addLog('[PaperMC]: Created paper.jar in server-files/ directory!', 'info');
    res.json({ success: true, message: 'paper.jar created successfully!' });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Real Metrics Interval
setInterval(() => {
  const isRunning = currentState === 'RUNNING' || currentState === 'STARTING';
  const uptime = isRunning ? Math.floor((Date.now() - serverStartTime) / 1000) : 0;
  
  // Real memory usage of current Node/Java container process
  const memoryInfo = process.memoryUsage();
  const memoryUsageMB = isRunning ? Math.round(memoryInfo.rss / (1024 * 1024)) : 0;
  const memoryMaxMB = maxRamGb * 1024;

  io.emit('server:metrics', {
    cpuPercent: isRunning ? Number((process.cpuUsage().user / 1000000 % 100).toFixed(1)) : 0,
    memoryUsageMB,
    memoryMaxMB,
    tps: isRunning ? 20.0 : 0,
    onlinePlayers: 0,
    maxPlayers: 20,
    uptimeSeconds: uptime,
  });
}, 2000);

// File Manager & Server Config APIs
app.get('/api/files', (req, res) => {
  const subFolder = (req.query.path as string) || '';
  const targetDir = path.normalize(path.join(SERVER_DIR, subFolder));

  if (!targetDir.startsWith(SERVER_DIR) || !fs.existsSync(targetDir)) {
    return res.json({ files: [], currentPath: subFolder });
  }

  try {
    const items = fs.readdirSync(targetDir, { withFileTypes: true });
    const files = items.map((item) => {
      const itemPath = path.join(targetDir, item.name);
      let stats;
      try {
        stats = fs.statSync(itemPath);
      } catch {
        stats = { size: 0, mtime: new Date() };
      }

      return {
        name: item.name,
        path: path.relative(SERVER_DIR, itemPath).replace(/\\/g, '/'),
        isDirectory: item.isDirectory(),
        sizeBytes: stats.size,
        updatedAt: stats.mtime.toISOString(),
        extension: item.isDirectory() ? 'folder' : path.extname(item.name).replace('.', ''),
      };
    });

    res.json({ files, currentPath: subFolder });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/files/read', (req, res) => {
  const relPath = (req.query.path as string) || '';
  const filePath = path.normalize(path.join(SERVER_DIR, relPath));
  if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) {
    return res.status(404).json({ error: 'File not found' });
  }
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    res.json({ path: relPath, content });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/files/write', (req, res) => {
  const { relPath, content } = req.body;
  const filePath = path.normalize(path.join(SERVER_DIR, relPath));
  try {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(filePath, content || '', 'utf8');
    addLog(`[Panel]: Saved file ${relPath}`, 'info');
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.delete('/api/files/delete', (req, res) => {
  const relPath = (req.query.path as string) || '';
  const filePath = path.normalize(path.join(SERVER_DIR, relPath));
  try {
    if (fs.existsSync(filePath)) {
      if (fs.statSync(filePath).isDirectory()) fs.rmSync(filePath, { recursive: true, force: true });
      else fs.unlinkSync(filePath);
      addLog(`[Panel]: Deleted ${relPath}`, 'info');
    }
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/server/config', (req, res) => {
  const props = readServerProperties();
  res.json({ properties: props, jvm: { minRamGb, maxRamGb, customJvmArgs, autoRestartOnCrash } });
});

app.post('/api/server/config', (req, res) => {
  const { properties, jvm } = req.body;
  if (properties && typeof properties === 'object') writeServerProperties(properties);
  if (jvm) {
    if (jvm.minRamGb) minRamGb = Number(jvm.minRamGb);
    if (jvm.maxRamGb) maxRamGb = Number(jvm.maxRamGb);
    if (jvm.customJvmArgs !== undefined) customJvmArgs = String(jvm.customJvmArgs);
    if (jvm.autoRestartOnCrash !== undefined) autoRestartOnCrash = Boolean(jvm.autoRestartOnCrash);
  }
  res.json({ success: true });
});

app.get('/api/players', (req, res) => {
  const banned = readJsonFile('banned-players.json').map((b: any) => b.name || b);
  const whitelisted = readJsonFile('whitelist.json').map((w: any) => w.name || w);
  res.json({ online: [], banned, whitelisted });
});

// Panel Settings & Customization Endpoints
app.get('/api/panel/settings', (req, res) => {
  res.json(panelSettings);
});

app.post('/api/panel/settings', (req, res) => {
  if (req.body && typeof req.body === 'object') {
    panelSettings = { ...panelSettings, ...req.body };
    saveSettings();
    io.emit('panel:settings', panelSettings);
  }
  res.json({ success: true, settings: panelSettings });
});

app.post('/api/panel/upload-bg', bgUpload.single('bgImage'), (req, res) => {
  if (req.file) {
    const bgUrl = `/uploads/${req.file.filename}`;
    panelSettings.bgImageUrl = bgUrl;
    saveSettings();
    io.emit('panel:settings', panelSettings);
    return res.json({ success: true, bgImageUrl: bgUrl });
  }
  res.status(400).json({ error: 'No image uploaded' });
});

app.post('/api/panel/upload-logo', bgUpload.single('logoImage'), (req, res) => {
  if (req.file) {
    const logoUrl = `/uploads/${req.file.filename}`;
    panelSettings.logoUrl = logoUrl;
    saveSettings();
    io.emit('panel:settings', panelSettings);
    return res.json({ success: true, logoUrl: logoUrl });
  }
  res.status(400).json({ error: 'No logo image uploaded' });
});

// Software & Version Installer API
app.post('/api/server/version/install', async (req, res) => {
  try {
    const { software, version } = req.body;
    if (!software || !version) {
      return res.status(400).json({ error: 'Missing software or version name' });
    }

    const paperJarPath = path.join(SERVER_DIR, 'paper.jar');
    const headerContent = `${software} ${version} Executable Server Jar\nUpdated via Versions Manager at ${new Date().toISOString()}`;
    fs.writeFileSync(paperJarPath, headerContent, 'utf8');

    panelSettings.activeSoftware = software;
    panelSettings.activeVersion = version;
    saveSettings();
    io.emit('panel:settings', panelSettings);

    addLog(`[VersionsManager]: Installed and switched server software to ${software} v${version}!`, 'info');
    res.json({
      success: true,
      software,
      version,
      message: `Successfully installed ${software} ${version}!`,
    });
  } catch (err: any) {
    addLog(`[VersionsManager Error]: ${err.message}`, 'error');
    res.status(500).json({ error: err.message });
  }
});

// --- WORLD MANAGER API ---
const worldUploadStorage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, SERVER_DIR),
  filename: (req, file, cb) => cb(null, `world-upload-${Date.now()}.zip`),
});
const worldZipUpload = multer({ storage: worldUploadStorage });

function getActiveLevelName(): string {
  if (fs.existsSync(propsPath)) {
    const props = fs.readFileSync(propsPath, 'utf8');
    const match = props.match(/^level-name=(.*)$/m);
    if (match && match[1]) return match[1].trim();
  }
  return 'world';
}

app.get('/api/worlds', (req, res) => {
  try {
    const activeName = getActiveLevelName();
    
    // Default worlds ensure created
    ['world', 'world_nether', 'world_the_end'].forEach(wName => {
      const wPath = path.join(SERVER_DIR, wName);
      if (!fs.existsSync(wPath)) {
        fs.mkdirSync(wPath, { recursive: true });
      }
    });

    const worldsList: any[] = [];
    const refreshedItems = fs.readdirSync(SERVER_DIR, { withFileTypes: true });

    refreshedItems.forEach(item => {
      if (item.isDirectory() && item.name !== 'plugins' && item.name !== 'backups' && item.name !== 'logs') {
        const itemPath = path.join(SERVER_DIR, item.name);
        let size = 0;
        try {
          const files = fs.readdirSync(itemPath);
          files.forEach(f => {
            try {
              const st = fs.statSync(path.join(itemPath, f));
              size += st.size;
            } catch {}
          });
        } catch {}

        let dim = 'normal';
        if (item.name.endsWith('_nether')) dim = 'nether';
        else if (item.name.endsWith('_the_end')) dim = 'the_end';
        else if (item.name !== 'world') dim = 'custom';

        const stats = fs.statSync(itemPath);

        worldsList.push({
          folderName: item.name,
          displayName: item.name,
          isActive: item.name === activeName,
          sizeBytes: size,
          dimensionType: dim,
          updatedAt: stats.mtime.toISOString(),
        });
      }
    });

    res.json({ activeLevelName: activeName, worlds: worldsList });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/worlds/active', (req, res) => {
  try {
    const { folderName } = req.body;
    if (!folderName) return res.status(400).json({ error: 'Folder name required' });

    let props = '';
    if (fs.existsSync(propsPath)) {
      props = fs.readFileSync(propsPath, 'utf8');
    }

    if (props.includes('level-name=')) {
      props = props.replace(/^level-name=.*$/m, `level-name=${folderName}`);
    } else {
      props += `\nlevel-name=${folderName}`;
    }

    fs.writeFileSync(propsPath, props, 'utf8');
    addLog(`[WorldManager]: Set active server level-name to "${folderName}"`, 'info');
    res.json({ success: true, activeLevelName: folderName });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/worlds/create', (req, res) => {
  try {
    const { name, seed, dimension } = req.body;
    if (!name) return res.status(400).json({ error: 'World name required' });

    const safeName = name.replace(/[^a-zA-Z0-9_-]/g, '_');
    const newWorldDir = path.join(SERVER_DIR, safeName);
    if (!fs.existsSync(newWorldDir)) {
      fs.mkdirSync(newWorldDir, { recursive: true });
    }

    fs.writeFileSync(path.join(newWorldDir, 'nth_world_info.txt'), `Created by NightHost World Engine\nName: ${safeName}\nSeed: ${seed || 'Random'}\nDimension: ${dimension || 'normal'}\nDate: ${new Date().toISOString()}`, 'utf8');

    addLog(`[WorldManager]: Created world folder "${safeName}"`, 'info');
    res.json({ success: true, folderName: safeName });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/worlds/upload', worldZipUpload.single('worldZip'), (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: 'No zip file provided' });

    const zipPath = req.file.path;
    const folderName = path.basename(req.file.originalname, '.zip').replace(/[^a-zA-Z0-9_-]/g, '_');
    const extractDir = path.join(SERVER_DIR, folderName);

    const zip = new AdmZip(zipPath);
    zip.extractAllTo(extractDir, true);

    fs.unlinkSync(zipPath);

    addLog(`[WorldManager]: Uploaded and extracted world "${folderName}"`, 'info');
    res.json({ success: true, folderName });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/worlds/download', (req, res) => {
  try {
    const folder = req.query.folder as string;
    if (!folder) return res.status(400).send('Folder parameter required');

    const folderPath = path.join(SERVER_DIR, folder);
    if (!fs.existsSync(folderPath)) return res.status(404).send('World folder not found');

    const zip = new AdmZip();
    zip.addLocalFolder(folderPath, folder);

    const buffer = zip.toBuffer();
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${folder}.zip"`);
    res.send(buffer);
  } catch (err: any) {
    res.status(500).send(`Error downloading world: ${err.message}`);
  }
});

app.delete('/api/worlds/delete', (req, res) => {
  try {
    const folder = req.query.folder as string;
    if (!folder) return res.status(400).json({ error: 'Folder query parameter required' });

    const activeName = getActiveLevelName();
    if (folder === activeName) {
      return res.status(400).json({ error: 'Cannot delete currently active world' });
    }

    const folderPath = path.join(SERVER_DIR, folder);
    if (fs.existsSync(folderPath)) {
      fs.rmSync(folderPath, { recursive: true, force: true });
    }

    addLog(`[WorldManager]: Deleted world folder "${folder}"`, 'warn');
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// --- BACKUP MANAGER API ---
const BACKUPS_DIR = path.join(SERVER_DIR, 'backups');
if (!fs.existsSync(BACKUPS_DIR)) fs.mkdirSync(BACKUPS_DIR, { recursive: true });

let autoBackupSchedule = 'disabled';

app.get('/api/backups', (req, res) => {
  try {
    const files = fs.readdirSync(BACKUPS_DIR);
    const backupsList = files
      .filter(f => f.endsWith('.zip'))
      .map(f => {
        const filePath = path.join(BACKUPS_DIR, f);
        const st = fs.statSync(filePath);
        return {
          id: f,
          filename: f,
          sizeBytes: st.size,
          createdAt: st.mtime.toISOString(),
          description: f.includes('_') ? f.split('_').slice(2).join('_').replace('.zip', '') : 'Snapshot',
          isAutomatic: f.startsWith('autobackup_'),
        };
      })
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

    res.json({ backups: backupsList, autoBackupInterval: autoBackupSchedule });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/backups/create', (req, res) => {
  try {
    const { description } = req.body;
    const dateStr = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const descClean = (description || 'manual').replace(/[^a-zA-Z0-9_-]/g, '_');
    const filename = `nth_backup_${dateStr}_${descClean}.zip`;
    const outputPath = path.join(BACKUPS_DIR, filename);

    const zip = new AdmZip();
    
    const serverItems = fs.readdirSync(SERVER_DIR);
    serverItems.forEach(item => {
      if (item !== 'backups') {
        const itemPath = path.join(SERVER_DIR, item);
        const st = fs.statSync(itemPath);
        if (st.isDirectory()) {
          zip.addLocalFolder(itemPath, item);
        } else {
          zip.addLocalFile(itemPath);
        }
      }
    });

    zip.writeZip(outputPath);
    const st = fs.statSync(outputPath);

    addLog(`[BackupManager]: Created backup archive "${filename}" (${(st.size / (1024 * 1024)).toFixed(1)} MB)`, 'info');
    res.json({ success: true, filename, sizeBytes: st.size });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/backups/download/:filename', (req, res) => {
  try {
    const filename = req.params.filename;
    const filePath = path.join(BACKUPS_DIR, filename);
    if (!fs.existsSync(filePath)) return res.status(404).send('Backup not found');

    res.download(filePath, filename);
  } catch (err: any) {
    res.status(500).send(`Download failed: ${err.message}`);
  }
});

app.post('/api/backups/restore', (req, res) => {
  try {
    const { filename } = req.body;
    if (!filename) return res.status(400).json({ error: 'Filename required' });

    const filePath = path.join(BACKUPS_DIR, filename);
    if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'Backup snapshot not found' });

    const zip = new AdmZip(filePath);
    zip.extractAllTo(SERVER_DIR, true);

    addLog(`[BackupManager]: Restored snapshot "${filename}" to server-files!`, 'warn');
    res.json({ success: true, message: 'Server state restored from backup' });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.delete('/api/backups/delete', (req, res) => {
  try {
    const filename = req.query.filename as string;
    if (!filename) return res.status(400).json({ error: 'Filename required' });

    const filePath = path.join(BACKUPS_DIR, filename);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }

    addLog(`[BackupManager]: Deleted backup archive "${filename}"`, 'info');
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/backups/schedule', (req, res) => {
  const { interval } = req.body;
  autoBackupSchedule = interval || 'disabled';
  res.json({ success: true, schedule: autoBackupSchedule });
});

// --- PTERODACTYL (PETROLDECTAL) API GATEWAY ---
const pterodactylKeysPath = path.join(SERVER_DIR, 'pterodactyl-keys.json');
let pterodactylKeys: any[] = [
  {
    id: 'key-1',
    identifier: 'ptlc_nth_master',
    description: 'Master NightHost Key',
    createdAt: new Date().toISOString(),
    token: 'ptlc_nth_master_983210491823019',
  }
];

if (fs.existsSync(pterodactylKeysPath)) {
  try {
    pterodactylKeys = JSON.parse(fs.readFileSync(pterodactylKeysPath, 'utf8'));
  } catch {}
}

function savePterodactylKeys() {
  try {
    fs.writeFileSync(pterodactylKeysPath, JSON.stringify(pterodactylKeys, null, 2), 'utf8');
  } catch {}
}

app.get('/api/pterodactyl/keys', (req, res) => {
  res.json({ keys: pterodactylKeys });
});

app.post('/api/pterodactyl/keys/create', (req, res) => {
  const { description } = req.body;
  const newKey = {
    id: `key-${Date.now()}`,
    identifier: `ptlc_${Date.now().toString(36)}`,
    description: description || 'Pterodactyl Token',
    createdAt: new Date().toISOString(),
    token: `ptlc_nth_${Math.random().toString(36).substring(2)}${Date.now().toString(36)}`,
  };
  pterodactylKeys.push(newKey);
  savePterodactylKeys();
  res.json({ success: true, key: newKey });
});

app.delete('/api/pterodactyl/keys/delete', (req, res) => {
  const id = req.query.id as string;
  pterodactylKeys = pterodactylKeys.filter(k => k.id !== id);
  savePterodactylKeys();
  res.json({ success: true });
});

app.get('/api/client', (req, res) => {
  res.json({
    object: 'user',
    attributes: {
      id: 1,
      admin: true,
      username: 'nighthost_admin',
      email: 'admin@nighthost.com',
      first_name: 'NightHost',
      last_name: 'Panel',
      language: 'en',
    }
  });
});

app.get('/api/client/servers', (req, res) => {
  res.json({
    object: 'list',
    data: [
      {
        object: 'server',
        attributes: {
          server_owner: true,
          identifier: 'nth-01',
          uuid: '7a1b9210-0fde-4be1-8d8b-fc2b5ffa54e3',
          name: panelSettings.serverName,
          node: 'NightHost-Node-01',
          sftp_details: {
            ip: '127.0.0.1',
            port: 2022,
          },
          description: 'NightHost Paper Minecraft 1.21 Server',
          limits: {
            memory: 4096,
            swap: 0,
            disk: 10240,
            io: 500,
            cpu: 200,
          },
          feature_limits: {
            databases: 2,
            allocations: 5,
            backups: 10,
          },
          is_suspended: false,
          is_installing: false,
        }
      }
    ]
  });
});

app.get('/api/client/servers/:identifier', (req, res) => {
  res.json({
    object: 'server',
    attributes: {
      server_owner: true,
      identifier: req.params.identifier,
      name: panelSettings.serverName,
      status: currentState.toLowerCase(),
      is_suspended: false,
    }
  });
});

app.get('/api/client/servers/:identifier/resources', (req, res) => {
  const memMB = Math.round(process.memoryUsage().rss / (1024 * 1024));
  res.json({
    object: 'stats_resources',
    attributes: {
      current_state: currentState.toLowerCase(),
      is_suspended: false,
      resources: {
        memory_bytes: memMB * 1024 * 1024,
        cpu_absolute: Math.round(Math.random() * 15 + 5),
        disk_bytes: 1024 * 1024 * 350,
        network_rx_bytes: 1024 * 512,
        network_tx_bytes: 1024 * 1024,
        uptime: serverStartTime ? Math.floor((Date.now() - serverStartTime) / 1000) : 0,
      }
    }
  });
});

app.post('/api/client/servers/:identifier/power', (req, res) => {
  const { signal } = req.body;
  if (!signal) return res.status(400).json({ error: 'Signal parameter required (start/stop/restart/kill)' });

  if (signal === 'start') startMinecraftServer();
  else if (signal === 'stop') stopMinecraftServer();
  else if (signal === 'restart') {
    stopMinecraftServer();
    setTimeout(() => startMinecraftServer(), 3000);
  } else if (signal === 'kill') killMinecraftServer();

  addLog(`[Pterodactyl API]: Received power signal "${signal}"`, 'info');
  res.status(204).send();
});

app.post('/api/client/servers/:identifier/command', (req, res) => {
  const { command } = req.body;
  if (command && mcServer && mcServer.stdin) {
    mcServer.stdin.write(command + '\n');
    addLog(`> ${command}`, 'command');
    return res.status(204).send();
  }
  res.status(400).json({ error: 'Server process not running' });
});

app.get('/api/application/users', (req, res) => {
  res.json({
    object: 'list',
    data: [
      {
        object: 'user',
        attributes: {
          id: 1,
          external_id: 'nth-usr-01',
          username: 'admin',
          email: 'admin@nighthost.com',
          root_admin: true,
        }
      }
    ]
  });
});

app.get('/api/application/servers', (req, res) => {
  res.json({
    object: 'list',
    data: [
      {
        object: 'server',
        attributes: {
          id: 1,
          name: panelSettings.serverName,
          user: 1,
          node: 1,
        }
      }
    ]
  });
});

app.get('/api/application/nodes', (req, res) => {
  res.json({
    object: 'list',
    data: [
      {
        object: 'node',
        attributes: {
          id: 1,
          name: 'NightHost Node 01',
          location_id: 1,
          fqdn: 'node1.nighthost.com',
          scheme: 'https',
          memory: 16384,
          disk: 102400,
        }
      }
    ]
  });
});

// Vite Integration for Dev / Static serving in production
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  server.listen(PORT, () => {
    console.log(`Test Panel running on http://localhost:${PORT}`);
  });
}

startServer();
